backend:
  name: turbo-github
  repo: uuoue/uuoue.github.io
  branch: main

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "标题"
        name: "title"
        widget: "string"

      - label: "日期"
        name: "date"
        widget: "datetime"

      - label: "分类"
        name: "categories"
        widget: "list"
        required: false

      - label: "标签"
        name: "tags"
        widget: "list"
        required: false

      - label: "正文"
        name: "body"
        widget: "markdown"